# Generated by Django 4.1.3 on 2022-11-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_auth',
            field=models.CharField(choices=[('NONE', 'NONE'), ('GOOGLE', 'GOOGLE')], default='NONE', max_length=20),
        ),
    ]
