# Generated by Django 4.1.3 on 2022-11-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_is_verified_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
